# Generated by Django 4.0.4 on 2022-05-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_users_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='house_number',
        ),
    ]
