# Generated by Django 4.0.4 on 2022-05-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_address_zip_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.address",
            ),
        ),
    ]
